# Generated by Django 2.2.1 on 2019-06-14 06:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(default='123@xyz.org', max_length=254)),
                ('dept', models.CharField(choices=[('department1', 'department1'), ('department2', 'department2'), ('department3', 'department3'), ('Other', 'Other')], default='Other', max_length=15)),
                ('complaint', models.CharField(max_length=1000)),
            ],
        ),
    ]
