<<<<<<< HEAD
# Generated by Django 2.0.2 on 2019-06-10 06:18

from django.db import migrations, models
import django.utils.timezone
=======
# Generated by Django 2.2.1 on 2019-06-07 06:00

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 642a1e5a6f1e442b0b6b91cdbd0bcfaa6b902910


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(default='123@xyz.org', max_length=254)),
                ('complaint', models.CharField(max_length=1000)),
=======
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(default='Other', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.CharField(max_length=8)),
                ('grevience', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_notes', models.CharField(default=' ', max_length=250)),
                ('private_notes', models.CharField(default=' ', max_length=250)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaint.department')),
>>>>>>> 642a1e5a6f1e442b0b6b91cdbd0bcfaa6b902910
            ],
        ),
    ]
