# Generated by Django 2.0.2 on 2019-06-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='author',
        ),
    ]
