# Generated by Django 2.2.1 on 2019-06-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('status1', 'status1'), ('status2', 'status2'), ('status3', 'status3')], default='status1', max_length=15),
        ),
    ]
