# Generated by Django 2.0.2 on 2019-06-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolution',
            field=models.CharField(default='res', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_by',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
