# Generated by Django 2.2.1 on 2019-06-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_auto_20190619_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('unresolved', 'unresolved'), ('resolved', 'resolved'), ('spam', 'spam')], default='unresolved', max_length=15),
        ),
    ]
