# Generated by Django 2.2.1 on 2019-06-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_complaint_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('unresolved', 'unresolved'), ('resolved', 'resolved'), ('spam', 'spam')], default='unresolved', max_length=15),
        ),
    ]
