# Generated by Django 2.0.2 on 2019-06-19 10:34

import complaint.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0004_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='channel',
            field=models.CharField(choices=[('MeeSeva', 'MeeSeva'), ('T-App Folio', 'T-App Folio'), ('T-Wallet', 'T-Wallet')], default='MeeSeva', max_length=25),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sle_date',
            field=models.DateTimeField(default=complaint.models.Complaint.two_days),
        ),
        migrations.AddField(
            model_name='complaint',
            name='stream',
            field=models.CharField(choices=[('Applications Issues', 'Application Issues'), ('Payment Issues', 'Payment Issues'), ('Data Fields', 'Data Fields'), ('Server Slowness', 'Server Slowness'), ('Others', 'Others')], default='Applications Issues', max_length=25),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='dept',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Food And Civil Supplies', 'Food And Civil Supplies'), ('GHMC', 'GHMC'), ('Commercial Taxes', 'Commercial Taxes'), ('SPDCL', 'SPDCL'), ('NPDCL', 'NPDCL'), ('Others', 'Others')], default='Revenue', max_length=25),
        ),
    ]
