# Generated by Django 2.0.2 on 2019-06-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_auto_20190619_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
