# Generated by Django 2.2.1 on 2019-06-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_auto_20190618_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='resolved_by',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
