# Generated by Django 2.0.2 on 2019-06-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0006_complaint_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
