# Generated by Django 2.0.2 on 2019-06-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0007_auto_20190619_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='file',
        ),
    ]
