# Generated by Django 2.0.2 on 2019-06-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0009_complaint_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='token',
        ),
    ]
