# Generated by Django 2.0.2 on 2019-06-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0010_remove_complaint_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
