# Generated by Django 2.0.2 on 2019-06-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Revenue', 'Revenue'), ('Food and Civil Supplies', 'Food and Civil Supplies'), ('GHMC', 'GHMC'), ('Commercial Taxes', 'Commercial Taxes'), ('SPDCL', 'SPDCL'), ('NPDCL', 'NPDCL'), ('Others', 'Others'), ('Citizen', 'Citizen')], default='Citizen', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='mode',
            field=models.CharField(choices=[('Mee Seva', 'Mee Seva'), ('T-App', 'T-App'), ('T-Wallet', 'T-Wallet'), ('Citizen', 'Citizen')], default='Citizen', max_length=255),
        ),
    ]
