# Generated by Django 2.0.2 on 2019-06-19 11:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190619_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mee Seva', 'Mee Seva'), ('T-App', 'T-App'), ('T-Wallet', 'T-Wallet'), ('Citizen', 'Citizen')], default='Citizen', max_length=255),
        ),
    ]
