# Generated by Django 2.0.2 on 2019-06-19 11:02

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190619_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Revenue', 'Revenue'), ('Food and Civil Supplies', 'Food and Civil Supplies'), ('GHMC', 'GHMC'), ('Commercial Taxes', 'Commercial Taxes'), ('SPDCL', 'SPDCL'), ('NPDCL', 'NPDCL'), ('Others', 'Others'), ('Citizen', 'Citizen')], default='Citizen', max_length=255),
        ),
    ]
